import type { EventCardData } from "@/components/ui/event-card";

export const mockEvents: EventCardData[] = [
  {
    id: "chuva-sp-sabado",
    title: "Vai chover em São Paulo no próximo sábado?",
    category: "Clima",
    status: "open",
    simPercent: 68,
    volume: 4320,
    deadline: "2 dias",
    source: "INMET",
  },
  {
    id: "ipca-abaixo-0-40",
    title: "IPCA de abril fica abaixo de 0,40%?",
    category: "Economia",
    status: "open",
    simPercent: 42,
    volume: 12800,
    deadline: "18 dias",
    source: "IBGE",
  },
  {
    id: "selic-manutencao",
    title: "Copom mantém a Selic no próximo encontro?",
    category: "Economia",
    status: "open",
    simPercent: 81,
    volume: 29400,
    deadline: "6 dias",
    source: "Banco Central do Brasil",
  },
  {
    id: "brasil-vence-eliminatorias",
    title: "Brasil vence a próxima rodada das Eliminatórias?",
    category: "Esportes",
    status: "open",
    simPercent: 73,
    volume: 8910,
    deadline: "4 dias",
    source: "CBF",
  },
  {
    id: "dolar-acima-6",
    title: "Dólar fecha acima de R$ 6,00 esta semana?",
    category: "Economia",
    status: "open",
    simPercent: 37,
    volume: 6650,
    deadline: "3 dias",
    source: "B3",
  },
  {
    id: "aprovacao-governo",
    title: "Aprovação do governo federal supera 40% em maio?",
    category: "Política",
    status: "open",
    simPercent: 29,
    volume: 3200,
    deadline: "22 dias",
    source: "Datafolha",
  },
];
